<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#INTRODUCTION" data-toc-modified-id="INTRODUCTION-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>INTRODUCTION</a></span></li><li><span><a href="#Libraries:-installation-and-importing" data-toc-modified-id="Libraries:-installation-and-importing-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Libraries: installation and importing</a></span><ul class="toc-item"><li><span><a href="#Exploratory-data-analysis-(EDA)" data-toc-modified-id="Exploratory-data-analysis-(EDA)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Exploratory data analysis (EDA)</a></span><ul class="toc-item"><li><span><a href="#Import-data" data-toc-modified-id="Import-data-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Import data</a></span></li><li><span><a href="#Get-some-information-about-the-dataframe-(completeness,-data-types,-column-names)" data-toc-modified-id="Get-some-information-about-the-dataframe-(completeness,-data-types,-column-names)-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Get some information about the dataframe (completeness, data types, column names)</a></span></li><li><span><a href="#Get-some-statistical-information" data-toc-modified-id="Get-some-statistical-information-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>Get some statistical information</a></span><ul class="toc-item"><li><span><a href="#Graph-to-show-outliers" data-toc-modified-id="Graph-to-show-outliers-2.1.3.1"><span class="toc-item-num">2.1.3.1&nbsp;&nbsp;</span>Graph to show outliers</a></span></li></ul></li><li><span><a href="#Get-all-possible-values-for-column-named-&quot;Country-Name&quot;-and-&quot;Country-code&quot;,-so-we-can-analyze-if-we-should-ignore-rows-(contries-in-this-case)" data-toc-modified-id="Get-all-possible-values-for-column-named-&quot;Country-Name&quot;-and-&quot;Country-code&quot;,-so-we-can-analyze-if-we-should-ignore-rows-(contries-in-this-case)-2.1.4"><span class="toc-item-num">2.1.4&nbsp;&nbsp;</span>Get all possible values for column named "Country Name" and "Country code", so we can analyze if we should ignore rows (contries in this case)</a></span></li></ul></li><li><span><a href="#Data-analysis" data-toc-modified-id="Data-analysis-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Data analysis</a></span><ul class="toc-item"><li><span><a href="#Descriptive-analytics:-graphs" data-toc-modified-id="Descriptive-analytics:-graphs-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Descriptive analytics: graphs</a></span><ul class="toc-item"><li><span><a href="#Bar-graphs" data-toc-modified-id="Bar-graphs-2.2.1.1"><span class="toc-item-num">2.2.1.1&nbsp;&nbsp;</span>Bar graphs</a></span></li><li><span><a href="#Pie-charts" data-toc-modified-id="Pie-charts-2.2.1.2"><span class="toc-item-num">2.2.1.2&nbsp;&nbsp;</span>Pie charts</a></span></li><li><span><a href="#World-map" data-toc-modified-id="World-map-2.2.1.3"><span class="toc-item-num">2.2.1.3&nbsp;&nbsp;</span>World map</a></span></li><li><span><a href="#Line-charts" data-toc-modified-id="Line-charts-2.2.1.4"><span class="toc-item-num">2.2.1.4&nbsp;&nbsp;</span>Line charts</a></span></li></ul></li></ul></li></ul></li></ul></div>

# INTRODUCTION

The visual representation of data is key to share and interpret information. Graphs are one of the most important elements in decision-making processes.
Here, you are going to have an example of different ways to show data and how different data can be interpreted based on the way it is presented.

# Libraries: installation and importing

If you don't have the needed libraries, you can import them by uncommenting one of the following lines and executing it. Once finished, comment that like again and try importing the libraries again.
Libraries are a collection of previously programmed functionalities and are useful to save time. In this example, we are going to execute a code and analyze the results.

In [ ]:
# pip --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org install pandas --user
# pip --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org install numpy --user
# pip --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org install matplotlib --user
# pip --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org install plotly --user

In [ ]:
# Import libraries
import pandas as pd # Dataframe (table) handling
import numpy as np # Numeric python, functions for calculations
import matplotlib.pyplot as plt # graphs
import plotly.express as px # more graphs
import plotly.graph_objects as go # and more graphs

# Directory path where the data is stored
path = 'https://raw.githubusercontent.com/prof-apartida/data-exercises/main/'

## Exploratory data analysis (EDA)

As mentioned, data exploration is crucial to determine if the information is accurate and has a minimum amount to get deeper insights.

### Import data

In [ ]:
df = pd.read_csv(path+'GDP_DATA.csv', header=2) # Import the data, use the data from the third row (the two forst rows have no important information, is noise)

# Function to remove the commas and convert them into numbers
def remove_commas(x):
    return x.replace(',', '') if isinstance(x, str) else x

df = df.applymap(remove_commas) # apply a function to the DataFrame
df = df.apply(pd.to_numeric, downcast='integer', errors='ignore') # downcast finds the minimum viable type for each column

df.head()# to see the first 5 rows

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.310056e+09,2.496648e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129059e+10,2.180847e+10,2.370702e+10,2.821004e+10,2.611879e+10,2.968217e+10,...,9.730435e+11,9.839370e+11,1.003679e+12,9.242525e+11,8.823551e+11,1.020647e+12,9.910223e+11,9.975340e+11,9.216459e+11,1.082096e+12
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,...,7.275704e+11,8.207927e+11,8.649905e+11,7.607345e+11,6.905464e+11,6.837487e+11,7.416899e+11,7.945430e+11,7.844457e+11,8.358084e+11
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249982e+11,1.334016e+11,1.372444e+11,8.721929e+10,4.984049e+10,6.897276e+10,7.779294e+10,6.930910e+10,5.361907e+10,7.254699e+10

### Get some information about the dataframe (completeness, data types, column names)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 66 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            133 non-null    float64
 5   1961            135 non-null    float64
 6   1962            137 non-null    float64
 7   1963            137 non-null    float64
 8   1964            137 non-null    float64
 9   1965            148 non-null    float64
 10  1966            151 non-null    float64
 11  1967            155 non-null    float64
 12  1968            160 non-null    float64
 13  1969            160 non-null    float64
 14  1970            169 non-null    float64
 15  1971            172 non-null    float64
 16  1972            172 non-null    float64
 17  1973            172 non-null    float64
 18  1974            173 non-null    float64
 19  1975            175 non-null    float64
 20  1976            176 non-null    float64
 21  1977            179 non-null    float64
 22  1978            178 non-null    float64
 23  1979            179 non-null    float64
 24  1980            191 non-null    float64
 25  1981            194 non-null    float64
 26  1982            195 non-null    float64
 27  1983            196 non-null    float64
 28  1984            197 non-null    float64
 29  1985            199 non-null    float64
 30  1986            201 non-null    float64
 31  1987            205 non-null    float64
 32  1988            210 non-null    float64
 33  1989            210 non-null    float64
 34  1990            226 non-null    float64
 35  1991            226 non-null    float64
 36  1992            227 non-null    float64
 37  1993            229 non-null    float64
 38  1994            231 non-null    float64
 39  1995            240 non-null    float64
 40  1996            240 non-null    float64
 41  1997            240 non-null    float64
 42  1998            242 non-null    float64
 43  1999            243 non-null    float64
 44  2000            247 non-null    float64
 45  2001            248 non-null    float64
 46  2002            253 non-null    float64
 47  2003            253 non-null    float64
 48  2004            253 non-null    float64
 49  2005            253 non-null    float64
 50  2006            254 non-null    float64
 51  2007            254 non-null    float64
 52  2008            255 non-null    float64
 53  2009            255 non-null    float64
 54  2010            256 non-null    float64
 55  2011            259 non-null    float64
 56  2012            257 non-null    float64
 57  2013            258 non-null    float64
 58  2014            259 non-null    float64
 59  2015            258 non-null    float64
 60  2016            257 non-null    float64
 61  2017            257 non-null    float64
 62  2018            257 non-null    float64
 63  2019            255 non-null    float64
 64  2020            251 non-null    float64
 65  2021            229 non-null    float64
dtypes: float64(62), object(4)
memory usage: 137.3+ KB

We can see that in 1960, we have only 133 non-null values, which means that we have a completeness of 50% (266 rows). In 2014 we have 259 non-null values, which means that we have a completeness of 97.4% in that year

### Get some statistical information

In [ ]:
df.describe() # get a summary of the numerical columns

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,1.330000e+02,1.350000e+02,1.370000e+02,1.370000e+02,1.370000e+02,1.480000e+02,1.510000e+02,1.550000e+02,1.600000e+02,1.600000e+02,...,2.570000e+02,2.580000e+02,2.590000e+02,2.580000e+02,2.570000e+02,2.570000e+02,2.570000e+02,2.550000e+02,2.510000e+02,2.290000e+02
mean,7.144431e+10,7.227617e+10,7.591834e+10,8.187843e+10,8.993111e+10,9.131323e+10,1.016025e+11,1.048530e+11,1.099793e+11,1.216207e+11,...,2.409844e+12,2.486600e+12,2.547072e+12,2.399580e+12,2.444096e+12,2.619181e+12,2.780139e+12,2.844702e+12,2.794879e+12,3.488195e+12
std,2.139668e+11,2.216008e+11,2.362059e+11,2.541180e+11,2.779094e+11,2.918706e+11,3.195597e+11,3.369514e+11,3.588648e+11,3.949848e+11,...,8.177023e+12,8.401499e+12,8.612101e+12,8.159025e+12,8.315368e+12,8.848379e+12,9.414787e+12,9.587406e+12,9.380763e+12,1.108532e+13
min,1.201201e+07,1.159201e+07,9.122751e+06,1.084010e+07,1.271247e+07,1.359393e+07,1.446908e+07,1.583518e+07,1.460000e+07,1.585000e+07,...,3.934562e+07,3.861749e+07,3.875969e+07,3.681166e+07,4.162950e+07,4.521766e+07,4.781829e+07,5.422315e+07,5.505471e+07,6.310096e+07
25%,5.083344e+08,5.111424e+08,5.317365e+08,5.161478e+08,5.425784e+08,5.863716e+08,6.380995e+08,6.264909e+08,6.454036e+08,6.912229e+08,...,8.709139e+09,8.748239e+09,9.169227e+09,8.589120e+09,8.595956e+09,9.252834e+09,9.880676e+09,1.083482e+10,1.033375e+10,1.401302e+10
50%,2.760747e+09,2.899655e+09,2.814319e+09,3.540403e+09,3.405333e+09,3.038595e+09,3.170500e+09,3.384063e+09,4.064739e+09,4.759106e+09,...,4.723165e+10,5.124299e+10,5.478285e+10,4.966795e+10,4.984049e+10,5.472660e+10,5.700371e+10,6.113687e+10,5.720378e+10,6.997032e+10
75%,3.115666e+10,2.963396e+10,2.906074e+10,3.368764e+10,3.097945e+10,2.848916e+10,3.024408e+10,3.076550e+10,3.420281e+10,3.741952e+10,...,5.524837e+11,5.447092e+11,5.445767e+11,5.005287e+11,5.156547e+11,5.410187e+11,5.554554e+11,5.706808e+11,6.499961e+11,1.018007e+12
max,1.392053e+12,1.448393e+12,1.550299e+12,1.671347e+12,1.829999e+12,1.993587e+12,2.163555e+12,2.302168e+12,2.484824e+12,2.740743e+12,...,7.548806e+13,7.760720e+13,7.970881e+13,7.517927e+13,7.646559e+13,8.140398e+13,8.641303e+13,8.765286e+13,8.490681e+13,9.610009e+13

In 1960, the <b>minimum GDP</b> value was 1.201201e+07 (12012010) USD, while the <b>maximum</b> value was 1.392053e+12 (1392053000000) USD.

In 2014, the <b>minimum GDP</b> value was 3.875969e+07 (38759690) USD, while the <b>maximum</b> value was 7.970881e+13 (79708810000000) USD.

#### Graph to show outliers

This is to identify the countries with GDP values that differ significantly from the rest of the sample

In [ ]:
year = '2014'
df1 = df[['Country Code','Country Name',year]]

fig = px.box(df1, y=year, hover_data=['Country Name'])
fig.show()

### Get all possible values for column named "Country Name" and "Country code", so we can analyze if we should ignore rows (contries in this case)

In [ ]:
pd.set_option('display.max_rows', None) # ask pandas to show all rows
pd.set_option('display.max_columns', None) # ask pandas to show all columns

df[['Country Name','Country Code']]

                                          Country Name Country Code
0                                                Aruba          ABW
1                          Africa Eastern and Southern          AFE
2                                          Afghanistan          AFG
3                           Africa Western and Central          AFW
4                                               Angola          AGO
5                                              Albania          ALB
6                                              Andorra          AND
7                                           Arab World          ARB
8                                 United Arab Emirates          ARE
9                                            Argentina          ARG
10                                             Armenia          ARM
11                                      American Samoa          ASM
12                                 Antigua and Barbuda          ATG
13                                           Australia          AUS
14                                             Austria          AUT
15                                          Azerbaijan          AZE
16                                             Burundi          BDI
17                                             Belgium          BEL
18                                               Benin          BEN
19                                        Burkina Faso          BFA
20                                          Bangladesh          BGD
21                                            Bulgaria          BGR
22                                             Bahrain          BHR
23                                         Bahamas The          BHS
24                              Bosnia and Herzegovina          BIH
25                                             Belarus          BLR
26                                              Belize          BLZ
27                                             Bermuda          BMU
28                                             Bolivia          BOL
29                                              Brazil          BRA
30                                            Barbados          BRB
31                                   Brunei Darussalam          BRN
32                                              Bhutan          BTN
33                                            Botswana          BWA
34                            Central African Republic          CAF
35                                              Canada          CAN
36                      Central Europe and the Baltics          CEB
37                                         Switzerland          CHE
38                                     Channel Islands          CHI
39                                               Chile          CHL
40                                               China          CHN
41                                       Cote d'Ivoire          CIV
42                                            Cameroon          CMR
43                                     Congo Dem. Rep.          COD
44                                          Congo Rep.          COG
45                                            Colombia          COL
46                                             Comoros          COM
47                                          Cabo Verde          CPV
48                                          Costa Rica          CRI
49                              Caribbean small states          CSS
50                                                Cuba          CUB
51                                             Curacao          CUW
52                                      Cayman Islands          CYM
53                                              Cyprus          CYP
54                                             Czechia          CZE
55                                             Germany          DEU
56                                            Djibouti          DJI
57                                            Dominica          DMA
58                                             Denmark          DNK
59                                  Dominican Republic          DOM
60                                             Algeria          DZA
61         East Asia & Pacific (excluding high income)          EAP
62                          Early-demographic dividend          EAR
63                                 East Asia & Pacific          EAS
64       Europe & Central Asia (excluding high income)          ECA
65                               Europe & Central Asia          ECS
66                                             Ecuador          ECU
67                                     Egypt Arab Rep.          EGY
68                                           Euro area          EMU
69                                             Eritrea          ERI
70                                               Spain          ESP
71                                             Estonia          EST
72                                            Ethiopia          ETH
73                                      European Union          EUU
74            Fragile and conflict affected situations          FCS
75                                             Finland          FIN
76                                                Fiji          FJI
77                                              France          FRA
78                                       Faroe Islands          FRO
79                                Micronesia Fed. Sts.          FSM
80                                               Gabon          GAB
81                                      United Kingdom          GBR
82                                             Georgia          GEO
83                                               Ghana          GHA
84                                           Gibraltar          GIB
85                                              Guinea          GIN
86                                          Gambia The          GMB
87                                       Guinea-Bissau          GNB
88                                   Equatorial Guinea          GNQ
89                                              Greece          GRC
90                                             Grenada          GRD
91                                           Greenland          GRL
92                                           Guatemala          GTM
93                                                Guam          GUM
94                                              Guyana          GUY
95                                         High income          HIC
96                                 Hong Kong SAR China          HKG
97                                            Honduras          HND
98              Heavily indebted poor countries (HIPC)          HPC
99                                             Croatia          HRV
100                                              Haiti          HTI
101                                            Hungary          HUN
102                                          IBRD only          IBD
103                                   IDA & IBRD total          IBT
104                                          IDA total          IDA
105                                          IDA blend          IDB
106                                          Indonesia          IDN
107                                           IDA only          IDX
108                                        Isle of Man          IMN
109                                              India          IND
110                                     Not classified          INX
111                                            Ireland          IRL
112                                  Iran Islamic Rep.          IRN
113                                               Iraq          IRQ
114                                            Iceland          ISL
115                                             Israel          ISR
116                                              Italy          ITA
117                                            Jamaica          JAM
118                                             Jordan          JOR
119                                              Japan          JPN
120                                         Kazakhstan          KAZ
121                                              Kenya          KEN
122                                    Kyrgyz Republic          KGZ
123                                           Cambodia          KHM
124                                           Kiribati          KIR
125                                St. Kitts and Nevis          KNA
126                                         Korea Rep.          KOR
127                                             Kuwait          KWT
128  Latin America & Caribbean (excluding high income)          LAC
129                                            Lao PDR          LAO
130                                            Lebanon          LBN
131                                            Liberia          LBR
132                                              Libya          LBY
133                                          St. Lucia          LCA
134                          Latin America & Caribbean          LCN
135       Least developed countries: UN classification          LDC
136                                         Low income          LIC
137                                      Liechtenstein          LIE
138                                          Sri Lanka          LKA
139                                Lower middle income          LMC
140                                Low & middle income          LMY
141                                            Lesotho          LSO
142                          Late-demographic dividend          LTE
143                                          Lithuania          LTU
144                                         Luxembourg          LUX
145                                             Latvia          LVA
146                                    Macao SAR China          MAC
147                           St. Martin (French part)          MAF
148                                            Morocco          MAR
149                                             Monaco          MCO
150                                            Moldova          MDA
151                                         Madagascar          MDG
152                                           Maldives          MDV
153                         Middle East & North Africa          MEA
154                                             Mexico          MEX
155                                   Marshall Islands          MHL
156                                      Middle income          MIC
157                                    North Macedonia          MKD
158                                               Mali          MLI
159                                              Malta          MLT
160                                            Myanmar          MMR
161  Middle East & North Africa (excluding high inc...          MNA
162                                         Montenegro          MNE
163                                           Mongolia          MNG
164                           Northern Mariana Islands          MNP
165                                         Mozambique          MOZ
166                                         Mauritania          MRT
167                                          Mauritius          MUS
168                                             Malawi          MWI
169                                           Malaysia          MYS
170                                      North America          NAC
171                                            Namibia          NAM
172                                      New Caledonia          NCL
173                                              Niger          NER
174                                            Nigeria          NGA
175                                          Nicaragua          NIC
176                                        Netherlands          NLD
177                                             Norway          NOR
178                                              Nepal          NPL
179                                              Nauru          NRU
180                                        New Zealand          NZL
181                                       OECD members          OED
182                                               Oman          OMN
183                                 Other small states          OSS
184                                           Pakistan          PAK
185                                             Panama          PAN
186                                               Peru          PER
187                                        Philippines          PHL
188                                              Palau          PLW
189                                   Papua New Guinea          PNG
190                                             Poland          POL
191                           Pre-demographic dividend          PRE
192                                        Puerto Rico          PRI
193                           Korea Dem. People's Rep.          PRK
194                                           Portugal          PRT
195                                           Paraguay          PRY
196                                 West Bank and Gaza          PSE
197                        Pacific island small states          PSS
198                          Post-demographic dividend          PST
199                                   French Polynesia          PYF
200                                              Qatar          QAT
201                                            Romania          ROU
202                                 Russian Federation          RUS
203                                             Rwanda          RWA
204                                         South Asia          SAS
205                                       Saudi Arabia          SAU
206                                              Sudan          SDN
207                                            Senegal          SEN
208                                          Singapore          SGP
209                                    Solomon Islands          SLB
210                                       Sierra Leone          SLE
211                                        El Salvador          SLV
212                                         San Marino          SMR
213                                            Somalia          SOM
214                                             Serbia          SRB
215         Sub-Saharan Africa (excluding high income)          SSA
216                                        South Sudan          SSD
217                                 Sub-Saharan Africa          SSF
218                                       Small states          SST
219                              Sao Tome and Principe          STP
220                                           Suriname          SUR
221                                    Slovak Republic          SVK
222                                           Slovenia          SVN
223                                             Sweden          SWE
224                                           Eswatini          SWZ
225                          Sint Maarten (Dutch part)          SXM
226                                         Seychelles          SYC
227                               Syrian Arab Republic          SYR
228                           Turks and Caicos Islands          TCA
229                                               Chad          TCD
230         East Asia & Pacific (IDA & IBRD countries)          TEA
231       Europe & Central Asia (IDA & IBRD countries)          TEC
232                                               Togo          TGO
233                                           Thailand          THA
234                                         Tajikistan          TJK
235                                       Turkmenistan          TKM
236  Latin America & the Caribbean (IDA & IBRD coun...          TLA
237                                        Timor-Leste          TLS
238  Middle East & North Africa (IDA & IBRD countries)          TMN
239                                              Tonga          TON
240                            South Asia (IDA & IBRD)          TSA
241          Sub-Saharan Africa (IDA & IBRD countries)          TSS
242                                Trinidad and Tobago          TTO
243                                            Tunisia          TUN
244                                            Turkiye          TUR
245                                             Tuvalu          TUV
246                                           Tanzania          TZA
247                                             Uganda          UGA
248                                            Ukraine          UKR
249                                Upper middle income          UMC
250                                            Uruguay          URY
251                                      United States          USA
252                                         Uzbekistan          UZB
253                     St. Vincent and the Grenadines          VCT
254                                       Venezuela RB          VEN
255                             British Virgin Islands          VGB
256                              Virgin Islands (U.S.)          VIR
257                                            Vietnam          VNM
258                                            Vanuatu          VUT
259                                              World          WLD
260                                              Samoa          WSM
261                                             Kosovo          XKX
262                                         Yemen Rep.          YEM
263                                       South Africa          ZAF
264                                             Zambia          ZMB
265                                           Zimbabwe          ZWE

In [ ]:
# Create a list excluding the non-valid "countries" (as they are not countries)
exclude = ['AFE', 'WLD','SAS','HIC','OED','PST','IBT','LMY','MIC','IBD','EAS','UMC','LTE','ECS','NAC','EAP','TEA','EUU','EMU','EAR','LMC','LCN','TLA','LAC','TEC','TSA','MEA','ECA','ARB','IDA','SSF','TSS','SSA','CEB','FCS','MNA','IDX','TMN','PRE','LDC','IDB','HPC','AFW','SST','LIC','OSS','CSS']

df_new = df[~df['Country Code'].isin(exclude)] # Create a dataframe that does not include the aforementioned codes
df_new.describe()

fig = px.box(df_new, y="1960", hover_data=['Country Name'])
fig.show()

## Data analysis
### Descriptive analytics: graphs
#### Bar graphs

In [ ]:
# Graph the GDP values by country of the year 2014
year = '2014'

fig = px.bar(df_new, x=year, y='Country Name', title="Countries' GDP")
fig.show()

fig = px.bar(df_new.sort_values(by=year, ascending=False).reset_index(drop=True), x=year, y='Country Name', title="Countries'  GDP") # Sort the table by ascending values
fig.show()

fig = px.bar(df_new.sort_values(by=year, ascending=False).head(15).reset_index(drop=True), x=year, y='Country Name', title='Top 15 countries by GDP')# Select the first 15 countries with higher GPD values
fig.show()

fig = px.bar(df_new.sort_values(by=year, ascending=False).tail(15).reset_index(drop=True), x=year, y='Country Name', title='Bottom 15 countries by GDP')# Select the first 15 countries with lower GPD values
fig.show()

#### Pie charts

World GDP contribution by country

In [ ]:
year = '2014'
fig = px.pie(df_new.sort_values(by=year, ascending=False).reset_index(drop=True), values=year, names='Country Name', title='Top countries by GDP in '+year)
fig.show()

# Pie chart 2
fig = px.pie(df_new.sort_values(by=year, ascending=False).head(5).reset_index(drop=True), values=year, names='Country Name', title='Pie chart 2: Top 5 countries by GDP in '+year)
fig.show()

# Pie chart 3
year = '1975'
fig = px.pie(df_new.sort_values(by=year, ascending=False).head(5).reset_index(drop=True), values=year, names='Country Name', title='Pie chart 3: Top 5 countries by GDP in '+year)
fig.show()

#### World map

In [ ]:
# Create a map to spatially illustrate the GDP values
year = '2014'

fig = px.choropleth(df_new, locations='Country Code', color=year, hover_data=['Country Name'], # hover is when you place the mouse over the map
                    color_continuous_scale='Reds',  # Define the color pallete
                    color_continuous_midpoint=np.mean(df_new[year]), # the midpoint color at the mean value
                    range_color=(np.min(df_new[year]),np.max(df_new[year])), # range of intensity from the minimum to the maximum valur
                    title="GDP in " + year + " by country" )
fig.show()


fig = px.choropleth(df_new, locations='Country Code', color=year, hover_data=['Country Name'], # hover is when you place the mouse over the map
                    color_continuous_scale='hot',  # Define the color pallete
                    color_continuous_midpoint=np.mean(df_new[year]), # the midpoint color at the mean value
                    range_color=(np.min(df_new[year]),np.max(df_new[year])), # range of intensity from the minimum to the maximum valur
                    title="GDP in " + year + " by country" )
fig.show()

In [ ]:
fig = px.colors.sequential.swatches_continuous()
fig.show()

<b> Table transposition: change the data from rows, to columns and viceversa </b><br>

We want to obtain data by country, and in the other table, the columns are by year, so we proceed to transpose the table.

In [ ]:
df_t = df_new.transpose() # transpose the table
df_t = df_t.reset_index() # reset the index
df_t.columns = df_t.iloc[1] # set the row with the country codes as column names, we select the country codes, so we have no problen on typing the name
df_t = df_t.drop(df_t.index[0:4]) # remove the first rows
df_t = df_t.rename(columns={'Country Code': 'Year'}) # Rename the column
df_t = df_t.reset_index(drop=True) # reset index and create a new one (drop=True)

df_t.head()

1,Year,ABW,AFG,AGO,ALB,AND,ARE,ARG,ARM,ASM,ATG,AUS,AUT,AZE,BDI,BEL,BEN,BFA,BGD,BGR,BHR,BHS,BIH,BLR,BLZ,BMU,BOL,BRA,BRB,BRN,BTN,BWA,CAF,CAN,CHE,CHI,CHL,CHN,CIV,CMR,COD,COG,COL,COM,CPV,CRI,CUB,CUW,CYM,CYP,CZE,DEU,DJI,DMA,DNK,DOM,DZA,ECU,EGY,ERI,ESP,EST,ETH,FIN,FJI,FRA,FRO,FSM,GAB,GBR,GEO,GHA,GIB,GIN,GMB,GNB,GNQ,GRC,GRD,GRL,GTM,GUM,GUY,HKG,HND,HRV,HTI,HUN,IDN,IMN,IND,INX,IRL,IRN,IRQ,ISL,ISR,ITA,JAM,JOR,JPN,KAZ,KEN,KGZ,KHM,KIR,KNA,KOR,KWT,LAO,LBN,LBR,LBY,LCA,LIE,LKA,LSO,LTU,LUX,LVA,MAC,MAF,MAR,MCO,MDA,MDG,MDV,MEX,MHL,MKD,MLI,MLT,MMR,MNE,MNG,MNP,MOZ,MRT,MUS,MWI,MYS,NAM,NCL,NER,NGA,NIC,NLD,NOR,NPL,NRU,NZL,OMN,PAK,PAN,PER,PHL,PLW,PNG,POL,PRI,PRK,PRT,PRY,PSE,PSS,PYF,QAT,ROU,RUS,RWA,SAU,SDN,SEN,SGP,SLB,SLE,SLV,SMR,SOM,SRB,SSD,STP,SUR,SVK,SVN,SWE,SWZ,SXM,SYC,SYR,TCA,TCD,TGO,THA,TJK,TKM,TLS,TON,TTO,TUN,TUR,TUV,TZA,UGA,UKR,URY,USA,UZB,VCT,VEN,VGB,VIR,VNM,VUT,WSM,XKX,YEM,ZAF,ZMB,ZWE
0,1960,NaN,537777811.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18606786874.0,6592693841.0,NaN,195999990.0,11658722591.0,226195579.0,330442817.0,4274893913.0,NaN,NaN,169803922.0,NaN,NaN,28071889.0,84466654.0,373879364.0,17030465539.0,NaN,NaN,NaN,30412309.0,112155599.0,40461721693.0,9522746719.0,NaN,4110000000.0,59716467625.0,546203562.0,614206071.0,3359404118.0,131731863.0,4031152977.0,NaN,NaN,507513830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,672399700.0,2723593385.0,2069465326.0,NaN,NaN,12072126075.0,NaN,NaN,5224102196.0,112328422.0,62225478001.0,NaN,NaN,141468978.0,73233967692.0,NaN,1217086835.0,NaN,NaN,NaN,NaN,NaN,4335186017.0,NaN,NaN,1043599900.0,NaN,170215248.0,1320796652.0,335650000.0,NaN,273187200.0,NaN,NaN,NaN,37029883876.0,NaN,1939329775.0,4199134390.0,1684121535.0,248434097.0,2598500000.0,40385288344.0,699050679.0,NaN,44307342950.0,NaN,791265459.0,NaN,637142866.0,NaN,12366564.0,3958190759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1409873950.0,34579308.0,NaN,703925706.0,NaN,NaN,NaN,2037150716.0,NaN,NaN,673081724.0,NaN,13040000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162956741.0,1916241997.0,NaN,NaN,449526873.0,4196092258.0,223854667.0,12276734172.0,5163271598.0,508334414.0,NaN,5485854792.0,NaN,3749265015.0,537147100.0,2571908062.0,7515886651.0,NaN,230496033.0,NaN,1691900000.0,NaN,3193200404.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119000024.0,NaN,1307333333.0,1003692375.0,704756305.0,NaN,322009472.0,NaN,NaN,180459937.0,NaN,NaN,NaN,99650000.0,NaN,NaN,15822585034.0,35076158.0,NaN,12012012.0,857704413.0,NaN,313582729.0,121128073.0,2760747472.0,NaN,NaN,NaN,NaN,535670128.0,NaN,13983572895.0,NaN,NaN,423008386.0,NaN,1242289239.0,543300000000.0,NaN,13066558.0,7779090909.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8748596504.0,713000000.0,1052990400.0
1,1961,NaN,548888896.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19683055213.0,7311749633.0,NaN,202999992.0,12400145222.0,235668222.0,350247237.0,4817580184.0,NaN,NaN,190098039.0,NaN,NaN,29964371.0,89249987.0,406684586.0,17275940449.0,NaN,NaN,NaN,32902337.0,123134584.0,40934952064.0,10712712465.0,NaN,4609727273.0,50056868958.0,618245639.0,652777614.0,3086746857.0,151675739.0,4540447761.0,NaN,NaN,490325182.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,654100200.0,2434727330.0,1753850417.0,NaN,NaN,13834300571.0,NaN,NaN,5921659485.0,116987785.0,67461644222.0,NaN,NaN,167637908.0,77741965703.0,NaN,1302521008.0,NaN,NaN,NaN,NaN,NaN,4961400439.0,NaN,NaN,1076699900.0,NaN,185848451.0,1383681651.0,356200000.0,NaN,271066000.0,NaN,NaN,NaN,39232435784.0,NaN,2088012282.0,4426949095.0,1831700364.0,253885656.0,3138500000.0,44842760293.0,748028839.0,NaN,53508617739.0,NaN,792959472.0,NaN,642857134.0,NaN,12483229.0,2417558289.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1444327731.0,35699286.0,NaN,704145671.0,NaN,NaN,NaN,2025689537.0,NaN,NaN,699161944.0,NaN,14160000000.0,NaN,NaN,NaN,NaN,584351384.0,NaN,NaN,NaN,NaN,159213140.0,NaN,174576508.0,1901868548.0,NaN,NaN,485785235.0,4467200336.0,240524723.0,13493833740.0,5632460937.0,531959562.0,NaN,5670064168.0,NaN,4118647627.0,599026300.0,2899654840.0,8171186335.0,NaN,244832035.0,NaN,1865100000.0,NaN,3417516639.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122000016.0,NaN,1419333333.0,1058975266.0,764634784.0,NaN,327834681.0,NaN,NaN,191659914.0,NaN,NaN,NaN,107700000.0,NaN,NaN,17212686615.0,43025199.0,NaN,11592012.0,945244972.0,NaN,333975339.0,126396470.0,3034043574.0,NaN,NaN,NaN,NaN,584961209.0,NaN,7988888889.0,NaN,NaN,441524109.0,NaN,1547388781.0,563300000000.0,NaN,13999883.0,8189090909.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9225996313.0,696285714.0,1096646600.0
2,1962,NaN,546666678.0,NaN,NaN,NaN,NaN,24450604877.0,NaN,NaN,NaN,19922723709.0,7756110210.0,NaN,213500006.0,13264015675.0,236434907.0,379567023.0,5081413340.0,NaN,NaN,212254902.0,NaN,NaN,31856923.0,94149986.0,444665186.0,19231747852.0,NaN,NaN,NaN,35643208.0,124482749.0,42227447632.0,11879982759.0,NaN,5416272727.0,47209359006.0,645284345.0,694247726.0,3779841429.0,166521240.0,4955543963.0,NaN,NaN,479180824.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,824100000.0,2001428328.0,1518208221.0,NaN,NaN,16138545209.0,NaN,NaN,6340580854.0,122906435.0,75607529810.0,NaN,NaN,182796536.0,81247564157.0,NaN,1382352941.0,NaN,NaN,NaN,NaN,9122751.0,5213047711.0,NaN,NaN,1143600000.0,NaN,194948375.0,1612346412.0,387750000.0,NaN,281896800.0,NaN,NaN,NaN,42161481858.0,NaN,2260349684.0,4693566416.0,1954634836.0,284916516.0,2510000000.0,50383891899.0,777712446.0,NaN,60723018684.0,NaN,868111400.0,NaN,660000009.0,NaN,12541562.0,2814318517.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1434156379.0,41859163.0,NaN,741509481.0,NaN,NaN,NaN,2379606422.0,NaN,NaN,739286907.0,NaN,15200000000.0,NaN,NaN,NaN,NaN,612517345.0,NaN,NaN,NaN,NaN,164271591.0,NaN,183116338.0,2001502679.0,NaN,NaN,531736493.0,4909302954.0,265291589.0,14647057370.0,6066976683.0,574091101.0,NaN,6077496268.0,NaN,4310163797.0,652120900.0,3286773188.0,4954529277.0,NaN,261184037.0,NaN,2094400000.0,NaN,3668222358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125000008.0,NaN,1541666667.0,1085475574.0,826244610.0,NaN,342721580.0,NaN,NaN,203531928.0,NaN,NaN,NaN,116150000.0,NaN,NaN,18667251380.0,45927061.0,NaN,12642027.0,1110565881.0,NaN,357635714.0,132237442.0,3308912797.0,NaN,NaN,NaN,NaN,619319197.0,NaN,8922222222.0,NaN,NaN,449012579.0,NaN,1710004407.0,605100000000.0,NaN,14524879.0,8946969697.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9813996079.0,693142857.0,1117601600.0
3,1963,NaN,751111191.0,NaN,NaN,NaN,NaN,18272123664.0,NaN,NaN,NaN,21539926084.0,8374175258.0,NaN,232749998.0,14260017387.0,253927646.0,394040588.0,5319458351.0,NaN,NaN,237745098.0,NaN,NaN,33749405.0,96366652.0,478805990.0,23287712878.0,NaN,NaN,NaN,38091151.0,129379098.0,45029988561.0,13063643796.0,NaN,5668187500.0,50706799903.0,761047046.0,718320701.0,6213185743.0,172233431.0,4836166667.0,NaN,NaN,511902137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,940799900.0,2702960118.0,1824344492.0,NaN,NaN,19074913948.0,NaN,NaN,6885920329.0,129454729.0,84759195106.0,NaN,NaN,154480244.0,86561961812.0,NaN,1540616246.0,NaN,NaN,NaN,NaN,10840095.0,5895278024.0,NaN,NaN,1262800000.0,NaN,175756869.0,1935298266.0,410200000.0,NaN,294883400.0,NaN,NaN,NaN,48421923459.0,NaN,2430843768.0,4928628018.0,1978437693.0,340061650.0,2992333333.0,57710743060.0,826690466.0,NaN,69498131797.0,NaN,926589349.0,NaN,728571437.0,NaN,12833226.0,3988784572.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1240672269.0,47039059.0,NaN,791140596.0,NaN,NaN,NaN,2657247327.0,NaN,NaN,759345863.0,NaN,16960000000.0,NaN,NaN,NaN,NaN,659976660.0,NaN,NaN,NaN,NaN,168186331.0,NaN,190816184.0,2510126748.0,NaN,NaN,586294761.0,5165489010.0,292916241.0,15891241386.0,6510239503.0,496947904.0,NaN,6638937283.0,NaN,4630827383.0,722784500.0,3600957771.0,5505055618.0,NaN,275968039.0,NaN,2333600000.0,NaN,3905734460.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128000000.0,NaN,1568333333.0,1122139637.0,917614008.0,NaN,348546952.0,NaN,NaN,216145936.0,NaN,NaN,NaN,125950000.0,NaN,NaN,20204870630.0,54128377.0,NaN,13923029.0,1200447408.0,NaN,371767003.0,143255785.0,3540403457.0,NaN,NaN,NaN,NaN,678235373.0,NaN,10355555556.0,NaN,NaN,516147799.0,NaN,1539681491.0,638600000000.0,NaN,13708219.0,9753333333.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10854195663.0,718714286.0,1159511700.0
4,1964,NaN,800000044.0,NaN,NaN,NaN,NaN,25605249382.0,NaN,NaN,NaN,23801097547.0,9169983886.0,NaN,260750008.0,15960106681.0,269818988.0,410321618.0,5386054619.0,NaN,NaN,266666667.0,NaN,NaN,36193826.0,107566651.0,539491477.0,20963733695.0,NaN,NaN,NaN,41613969.0,142025069.0,49377522897.0,14480556572.0,NaN,5982347826.0,59708343489.0,921063266.0,776650126.0,2881545273.0,185693725.0,5973366667.0,NaN,NaN,542578367.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1025599900.0,2909292864.0,2244146868.0,NaN,NaN,21343844644.0,NaN,NaN,7766655086.0,140032741.0,94007851047.0,NaN,NaN,215679855.0,94407558351.0,NaN,1731092437.0,NaN,NaN,NaN,NaN,12712471.0,6669673257.0,NaN,NaN,1299099900.0,NaN,194773377.0,2206466461.0,457000000.0,NaN,325281200.0,NaN,NaN,NaN,56480289941.0,NaN,2766608946.0,5379845648.0,2340521143.0,434267937.0,3405333333.0,63175417019.0,897931401.0,NaN,81749006382.0,NaN,998759334.0,NaN,782857129.0,NaN,13416555.0,3458939358.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1309747899.0,51938961.0,NaN,903158754.0,NaN,NaN,NaN,2798339769.0,NaN,NaN,802482183.0,NaN,20080000000.0,NaN,NaN,NaN,NaN,475197382.0,NaN,NaN,NaN,NaN,224495789.0,NaN,194736105.0,2674441396.0,NaN,NaN,582816358.0,5552822484.0,341973759.0,18699380731.0,7159202706.0,496098775.0,NaN,7274144351.0,NaN,5204955901.0,776137500.0,4356913870.0,5953766854.0,NaN,305312044.0,NaN,2570500000.0,NaN,4235608178.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129999994.0,NaN,1611333333.0,1188930568.0,894159153.0,NaN,371848115.0,NaN,NaN,229529913.0,NaN,NaN,NaN,134400000.0,NaN,NaN,22532416750.0,64979280.0,NaN,15393032.0,1339494267.0,NaN,392247518.0,166104068.0,3889129942.0,NaN,NaN,NaN,NaN,711893368.0,NaN,11177777778.0,NaN,NaN,589056604.0,NaN,1975701816.0,685800000000.0,NaN,14758210.0,8099318182.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11955995223.0,839428571.0,1217138000.0

#### Line charts

In [ ]:
# Let's see the total GDP progress of Qatar
country = 'QAT'

fig = go.Figure()
fig.add_trace(go.Scatter(x=df_t['Year'], y=df_t[country], mode='lines', name=country))
fig.update_layout(title=country + " GDP progress")
fig.show()

In [ ]:
# Now, let's compare it with USA
country1 = 'QAT'
country2 = 'JPN'

fig = go.Figure()
fig.add_trace(go.Scatter(x=df_t['Year'], y=df_t[country1], mode='lines', name=country1))
fig.add_trace(go.Scatter(x=df_t['Year'], y=df_t[country2], mode='lines', name=country2))
fig.update_layout(title="GDP comparison")
fig.show()